### ISSUE TITLE
deg <> rad function or variable 

### ISSUE THREAD

**Issue by masla84** [rabauke/harbour-babbage#4]
Is it possible to add a option for trigonometric functions to use degree or radiants as parameter?

- As global setting to use sin() directly with degrees
- or as predefined variable like deg2rad = pi/180 
- or a function deg2rad() / rad2deg().

Thanks for this really good piece of software for SailfishOS !

**Comment by rabauke** [comment]
Thanks for your feedback. This is feature worth to consider in a future update. As an intermediate solution, you can switch to the scientific calculator mode and enter the "°" sign (not sure if it is available on all keyboards) to indicate degrees. For example,

sin(90°)

yields 1.

**Comment by masla84** [comment]
Thank you for the info. Maybe it's worth to update the function help with that.

**Comment by rabauke** [comment]
Closed via d514eda57c1a55fea8e5dbecd4e4eb5c152510a3, which introduces two new functions, `deg` and `rad` for conversion between arc degree and radian.
